"""A frost impact: what a frost bolt leaves where it strikes. Built the way the game builds its ice hits
(fx_iceshard_hit, vfx_frostarrow_hit, vfx_ice_hit, measured in codex/vfx/archetypes.md): a spray of tiny pale-cyan lit
pixel bits that fall and bounce, a few small ice shards as mesh particles, a slow pale-blue frost mist, a handful of
cold glints and a flash, and a pale blue light for half a second (the game's frost light colour 0.455, 0.842, 1.0).
"""

EFFECT = {
    "name": "ecp_frost_impact",
    "category": "vfx.hit_material",
    "timeout": 5.0,
    "shake": {"strength": 0.4, "range": 10},
    "preview": {"seconds": 2.5, "distance": 3.5, "target_height": 0.5, "pitch": 18,
                "references": ["GameElements/Items/weapons/_res/staffs/fx/fx_iceshard_hit.prefab"],
                "reference_offset": [2.8, 0, 0]},
    "textures": {
        "ecp_frost_mist": {"make": "cloud", "args": {"px": 128, "seed": 21, "contrast": 0.6}},
        "ecp_frost_glint": {"make": "star", "args": {"px": 64}},
        "ecp_frost_glow": {"make": "point", "args": {"px": 128}},
    },
    "materials": {
        "ecp_frost_bits": {"shader": "lit"},                              # untextured: flat lit squares, as pixel_lit
        "ecp_frost_shard": {"shader": "opaque_lit", "colours": {"_Color": [0.78, 0.92, 1.0, 1]},
                            "floats": {"_Glossiness": 0.6}},
        "ecp_frost_mist": {"texture": "ecp_frost_mist", "shader": "lit", "soft": 1.0},
        "ecp_frost_glint": {"texture": "ecp_frost_glint", "shader": "legacy_additive"},
        "ecp_frost_glow": {"texture": "ecp_frost_glow", "shader": "legacy_additive"},
    },
    "meshes": {"ecp_frost_shard": {"kind": "shard", "seed": 3}},
    "systems": [
        {"name": "bits", "role": "pixel", "position": [0, 0.05, 0], "euler": [-90, 0, 0], "duration": 1.0, "space": "world",
         "max_particles": 200, "lifetime": (1.2, 2.0), "speed": (1.5, 4.0), "size": (0.035, 0.065), "gravity": 0.35,
         "colour": ([0.65, 0.95, 1.0, 0.5], [1, 1, 1, 1]),
         "shape": {"type": "cone", "angle": 55, "radius": 0.1},
         "emission": {"rate": 0, "bursts": [(0.0, 60)]},
         "limit": {"speed": 2.0, "drag": 0.6},
         "collision": {"type": "world", "bounce": 0.25, "dampen": 0.4},
         "colour_life": {"colour": [[0, 1, 1, 1], [1, 1, 1, 1]], "alpha": [[0, 1], [0.7, 1], [1, 0]]},
         "size_life": [[0, 1], [0.8, 1], [1, 0]],
         "rotation_life": (-300, 300),
         "renderer": {"material": "ecp_frost_bits", "max_size": 0.5}},
        {"name": "shards", "role": "debris", "position": [0, 0.1, 0], "euler": [-90, 0, 0], "duration": 1.0, "space": "world",
         "max_particles": 20, "lifetime": (1.6, 2.4), "speed": (2.0, 4.5), "size": (0.07, 0.15), "gravity": 0.8,
         "rotation": (0, 360), "colour": ([0.8, 0.92, 1, 1], [1, 1, 1, 1]),
         "shape": {"type": "cone", "angle": 45, "radius": 0.1},
         "emission": {"rate": 0, "bursts": [(0.0, 7)]},
         "collision": {"type": "world", "bounce": 0.3, "dampen": 0.3},
         "size_life": [[0, 1], [0.8, 1], [1, 0]],
         "rotation_life": (-360, 360),
         "renderer": {"mode": "mesh", "mesh": "ecp_frost_shard", "material": "ecp_frost_shard"}},
        {"name": "mist", "role": "smoke", "position": [0, 0.3, 0], "duration": 1.0, "space": "world", "max_particles": 12,
         "lifetime": (2.5, 3.8), "speed": (0.8, 2.0), "size": (1.4, 2.2), "rotation": (0, 360),
         "colour": [0.55, 0.83, 1.0, 0.3],
         "shape": {"type": "hemisphere", "radius": 0.3},
         "emission": {"rate": 0, "bursts": [(0.0, 5)]},
         "limit": {"speed": 0.2, "drag": 2.0},
         "colour_life": {"colour": [[0, 1, 1, 1], [1, 1, 1, 1]], "alpha": [[0, 0], [0.15, 1], [0.6, 0.6], [1, 0]]},
         "size_life": [[0, 0.5], [1, 1.0]],
         "rotation_life": (-12, 12),
         "renderer": {"material": "ecp_frost_mist", "max_size": 1.0}},
        {"name": "glints", "role": "spark", "position": [0, 0.3, 0], "duration": 1.0, "space": "world", "max_particles": 20,
         "lifetime": (0.3, 0.6), "speed": (1.0, 3.0), "size": (0.18, 0.36), "rotation": (0, 360),
         "colour": ([0.6, 0.85, 1.0, 1], [0.9, 0.97, 1.0, 1]),
         "shape": {"type": "sphere", "radius": 0.15},
         "emission": {"rate": 0, "bursts": [(0.0, 10)]},
         "limit": {"speed": 0.5, "drag": 3.0},
         "colour_life": {"colour": [[0, 1, 1, 1], [1, 1, 1, 1]], "alpha": [[0, 1], [1, 0]]},
         "renderer": {"material": "ecp_frost_glint", "max_size": 0.5}},
        {"name": "flash", "role": "flash", "position": [0, 0.35, 0], "duration": 0.5, "max_particles": 2,
         "lifetime": 0.2, "speed": 0, "size": 1.6, "colour": [0.45, 0.75, 1.0, 0.5], "shape": None,
         "emission": {"rate": 0, "bursts": [(0.0, 1)]},
         "colour_life": {"colour": [[0, 1, 1, 1], [1, 1, 1, 1]], "alpha": [[0, 1], [1, 0]]},
         "size_life": [[0, 0.7], [1, 1.0]],
         "renderer": {"material": "ecp_frost_glow", "max_size": 2.0}},
    ],
    "lights": [{"name": "light", "position": [0, 0.5, 0], "colour": [0.455, 0.842, 1.0], "intensity": 2.5, "range": 4.0,
                "flicker": {"intensity": 0.1, "speed": 10, "movement": 0.1, "ttl": 0.5, "fade": 0.4},
                "lod": {"distance": 40}}],
}
