using System;
using System.Collections.Generic;
using EliteCrafting.Core;
using YamlDotNet.RepresentationModel;

namespace EliteCrafting.Rules
{
    /// <summary>
    /// Reads an affix's <c>tiers</c> (classes-and-tiers.md section 3) in either form: a ladder map
    /// <c>{ count, from, min, max }</c> (flags: <c>{ count, from }</c>) generated by <see cref="TierLadder"/>, or explicit
    /// rows <c>[ { tier, level, min, max, weight } ]</c> where <c>tier</c> counts down (1 strongest) and <c>weight</c>
    /// defaults to the tier number. Either way the rows are stored by strength grade (1 = the weakest, T<c>k</c>) and
    /// sorted weakest first; k is the ladder's count, or the highest tier number the rows list.
    /// </summary>
    internal static class AffixTierParser
    {
        public static List<AffixTierDef> Parse(MapReader r, AffixDef def)
        {
            YamlNode? node = r.Node("tiers");
            if (node is YamlMappingNode map)
            {
                return Ladder(new MapReader(map, r.At("tiers"), r.Issues), def);
            }
            if (node is YamlSequenceNode seq && seq.Children.Count > 0)
            {
                return Rows(r, seq, def);
            }
            r.Issues.Error(r.At("tiers"), node ?? r.Map, "is required: a ladder { count, from, min, max } or a list of rows");
            return new List<AffixTierDef>();
        }

        private static List<AffixTierDef> Ladder(MapReader r, AffixDef def)
        {
            r.Unknown("count", "from", "min", "max");
            TierLadder.Spec spec = new TierLadder.Spec
            {
                Count = r.Int("count", 1, 1, TierLadder.MaxCount),
                From = r.Int("from", 1, 1, TierLadder.MaxLevel),
                Valued = def.Value != AffixValueType.Flag,
            };
            RequireKeys(r, "count", "from");
            if (!ReadLadderBounds(r, spec, def))
            {
                return new List<AffixTierDef>();
            }
            def.TierCount = spec.Count;
            return TierLadder.Rows(spec);
        }

        private static bool ReadLadderBounds(MapReader r, TierLadder.Spec spec, AffixDef def)
        {
            if (!spec.Valued)
            {
                return RefuseBounds(r);
            }
            if (!r.Has("min") || !r.Has("max"))
            {
                r.Error("min", "min and max are required");
                return false;
            }
            // Doubles from the text, not the float reads: the ladder must match the planning page digit for digit.
            spec.Min = Numbers.TryDouble(r.Str("min"), out double min) ? min : r.Float("min", 0f);
            spec.Max = Numbers.TryDouble(r.Str("max"), out double max) ? max : r.Float("max", 0f);
            spec.MinDecimals = Numbers.Decimals(r.Str("min") ?? "");
            spec.MaxDecimals = Numbers.Decimals(r.Str("max") ?? "");
            spec.WholeFlat = def.Value == AffixValueType.Flat && def.Unit == AffixUnit.None
                && spec.Min == Math.Floor(spec.Min) && spec.Max == Math.Floor(spec.Max);
            if (spec.Min > spec.Max)
            {
                r.Error("min", "min is above max");
                return false;
            }
            return true;
        }

        private static List<AffixTierDef> Rows(MapReader r, YamlSequenceNode seq, AffixDef def)
        {
            List<AffixTierDef> tiers = new List<AffixTierDef>();
            for (int i = 0; i < seq.Children.Count; i++)
            {
                AffixTierDef? tier = ParseRow(seq.Children[i], $"{r.At("tiers")}[{i}]", def.Value, r.Issues);
                if (tier != null)
                {
                    AddUnique(tiers, tier, seq.Children[i], r);
                }
            }
            int k = 0;
            tiers.ForEach(t => k = Math.Max(k, t.Shown));
            tiers.ForEach(t => t.Grade = k + 1 - t.Shown);
            tiers.Sort((a, b) => a.Grade.CompareTo(b.Grade));
            def.TierCount = k;
            WarnDescending(r, tiers, def.Value);
            return tiers;
        }

        private static AffixTierDef? ParseRow(YamlNode node, string path, AffixValueType valueType, RuleIssues issues)
        {
            if (!(node is YamlMappingNode map))
            {
                issues.Error(path, node, "a tier row should look like { tier: 1, level: 8, min: 2, max: 3 }");
                return null;
            }
            MapReader row = new MapReader(map, path, issues);
            row.Unknown("tier", "level", "min", "max", "weight");
            int shown = row.Int("tier", 1, 1, TierLadder.MaxCount);
            AffixTierDef tier = new AffixTierDef
            {
                Shown = shown,
                Level = row.Int("level", 1, 1, TierLadder.MaxLevel),
                Weight = row.Float("weight", shown, 0f),
            };
            RequireKeys(row, "tier", "level");
            return ReadRowBounds(row, tier, valueType) ? tier : null;
        }

        private static bool ReadRowBounds(MapReader row, AffixTierDef tier, AffixValueType valueType)
        {
            if (valueType == AffixValueType.Flag)
            {
                return RefuseBounds(row);
            }
            if (!row.Has("min") || !row.Has("max"))
            {
                row.Error("min", "min and max are required");
                return false;
            }
            tier.Min = row.Float("min", 0f);
            tier.Max = row.Float("max", 0f);
            tier.Decimals = Math.Min(2, Math.Max(Numbers.Decimals(row.Str("min") ?? ""), Numbers.Decimals(row.Str("max") ?? "")));
            if (tier.Min > tier.Max)
            {
                row.Error("min", "min is above max");
            }
            return true;
        }

        private static bool RefuseBounds(MapReader r)
        {
            if (r.Has("min") || r.Has("max"))
            {
                r.Error("min", "a flag inscription has no min or max");
            }
            return true;
        }

        private static void RequireKeys(MapReader r, params string[] keys)
        {
            foreach (string key in keys)
            {
                if (!r.Has(key))
                {
                    r.Issues.Error(r.At(key), r.Map, "is required");
                }
            }
        }

        private static void AddUnique(List<AffixTierDef> tiers, AffixTierDef tier, YamlNode node, MapReader r)
        {
            if (tiers.Exists(t => t.Shown == tier.Shown))
            {
                r.Issues.Error(r.At("tiers"), node, $"tier {tier.Shown} is listed twice");
                return;
            }
            tiers.Add(tier);
        }

        private static void WarnDescending(MapReader r, List<AffixTierDef> tiers, AffixValueType valueType)
        {
            for (int i = 1; valueType != AffixValueType.Flag && i < tiers.Count; i++)
            {
                if (tiers[i].Max < tiers[i - 1].Max)
                {
                    r.Warn("tiers", $"tier {tiers[i].Shown} rolls lower than the weaker tier {tiers[i - 1].Shown} (a typo? tier 1 is the strongest)");
                    return;
                }
            }
        }
    }
}
