"""Material families of soft and living things: leather, cloth, thatch, chitin, skin, plants (see
paint_families)."""
from paint_families_base import A, C, I, NATURE, P, PLANKS, R, W, s  # noqa: F401

FAMILIES = {
    "leather.leather": {
        "label": "tanned leather: straps, armour, grips, saddles",
        "region": "leather",
        "samples": [
            s(I + "helmets/_res/Bronze/helmet_leather_d.png"),
            s(I + "materials/_res/leatherscraps/leatherscraps_d.png"),
            s(A + "LoxArmor/model/LoxChest_D.png"),
            s(A + "LoxArmor/model/LoxLegs_D.png"),
            s(I + "utility/_res/BeltStrength/belt1_d.png", mask="nonmetal"),
            s(W + "bow/SpineSnap/model/SpineSnap_d.png", crop=(0.0, 0.42, 0.3, 0.95)),
            s(C + "Asksvin/Saddle/asksvinsaddle_d.png"),
        ]},
    "leather.hide": {
        "label": "raw hides and rugs, hair side down",
        "region": "leather",
        "samples": [
            s(I + "_res/Hide/hide01.png"),
            s(I + "_res/Hide/hide02.png"),
            s(I + "_res/Hide/bearhide_d.png"),
            s(I + "_res/Hide/troll_hide.png"),
            s(P + "MooseRug/model/moose_rug_d.png"),
            s(P + "SealRug/model/Sealrug_d.png"),
            s(P + "Asksvinrug/model/asksvinrug_d.png"),
            s(P + "Tanningrack/model/Tanningrack_d.png"),
        ]},
    "leather.fur": {
        "label": "fur and pelts",
        "region": "fur",
        "samples": [
            s(A + "SilverArmour/WolfCape_d.png"),
            s(A + "LoxCape/model/LoxCape_D.png"),
            s(R + "CastleBuildingKit/_res/rugs/rug_fur.png"),
            s(R + "CastleBuildingKit/_res/rugs/rug_wolf.png"),
            s(I + "_res/Hide/wolfhide_d.png"),
            s(P + "BjornRug/model/BjornRug_d.png"),
        ]},
    "cloth.linen": {
        "label": "woven cloth: linen, jute, wool; clothes, banners, sails, tents, rugs",
        "region": "cloth",
        "samples": [
            s(A + "ClothesMerchant/Clothes/model/ClothesCasual1_d.png"),
            s(A + "ClothesMerchant/Clothes/model/ClothesCasual4_d.png"),
            s(P + "JuteCarpet/jutecarpet_d.png"),
            s(P + "JuteCarpet/jutecarpet_blue_d.png"),
            s(P + "Banners/Model/Banner_1_borderRedWhite_d.png"),
            s("3rd party/VikingShip/Textures/sail_white.tga"),
            s("GameElements/Ships/_res/ShipTent/ShipTent_d.png"),
            s(A + "DeepNorth_capes/model/NordCape_d.png"),
            s(R + "Morkhalla/Rugs/morkhalla_rug1_d.png"),
            s(R + "TraderTent/model/TraderTent_d.png"),
            s(R + "HildirWagon/MarketProps/model/HildirFabrics1_d.png"),
        ]},
    "cloth.rope": {
        "label": "rope, thread, sinew lashing",
        "region": "rope",
        "samples": [
            s("GameElements/Cart/_res/rope_d.jpg"),
            s(I + "_res/NornThread/model/nornthread_d.png"),
        ]},
    "thatch.straw": {
        "label": "thatch and straw",
        "region": "primary",
        "samples": [
            s("world/textures/straw_roof.png"),
            s("world/textures/straw_roof_worn.png"),
            s("world/textures/straw_roof_corner.png"),
            s(P + "StrawFloor/model/strawfloor_d.png"),
            s(P + "Birdnest/model/birdnest_d.png"),
            s(A + "ClothesMerchant/Clothes/model/Harvester/strawhat_d.png"),
        ]},
    "chitin.chitin": {
        "label": "chitin and carapace",
        "region": "primary",
        "samples": [
            s(I + "materials/_res/chitin/chitin.png"),
            s(A + "CarapaceArmor/model/carapacearmor_d.png", mask="nonmetal"),
            s(I + "shields/_res/Shield_CarapaceRound/model/Shield_carapaceround_d.png"),
            s(C + "Seeker/model/seeker_d.png"),
            s(C + "SeekerBrute/model/seekerBrute_d.png"),
            s(C + "Seeker/gibs/Carapace_d.png"),
            s(C + "SeekerQueen/model/SeekerQueen_d.png"),
            s(C + "Deathsquito/model/Deathsquito_d.png"),
            s(C + "Tick/Model/material/Feasting_d.png"),
        ]},
    "skin.skin": {
        "label": "creature skin and hide on the body",
        "region": "skin",
        "samples": [
            s(C + "Troll/model/material/troll_diffuse.png", material=C + "Troll/model/material/troll.mat"),
            s(C + "Draugr/newmodel/Draugr_d.png"),
            s(C + "GreyDwarf/Materials/greydrawrf_diffuse.png"),
            s(C + "Goblin/material/goblin_d.png"),
            s(C + "GoblinBrute/model/GoblinBrute_d.png"),
            s(C + "Jotnar/model/Jotnar_d.png"),
            s(C + "Neck/material/neck_d.png"),
            s(C + "Player/model/old_PlayerCharacter2/PlayerCharacter_01.png"),
            s(C + "FrostTroll/model/frosttroll_d.png"),
            s(C + "Abomination/model/Rotvalta_d.png"),
            s(C + "Morgen/model/Morgen_d.png"),
            s(C + "Fenring/Model/Fenring_d.png"),
        ]},
    "skin.flesh": {
        "label": "raw meat, organs and flesh",
        "region": "skin",
        "samples": [
            s(I + "_res/BearMeat/model/bearmeat_uncooked_d.png"),
            s(I + "_res/DeerMeat/model/UncookedDeerMeat_d.png"),
            s("3rd party/Malbers Animations/Animals Packs/Models/Materials/raw_meat_d.png"),
            s(I + "materials/_res/entrails/entrails_d.png"),
            s(I + "materials/_res/SoftTissue/model/softtissue_d.png"),
            s(I + "_res/gdkingheart/heart.png"),
            s(I + "_res/MooseMeat/model/Moosemeat_d.png"),
            s(I + "_res/WolfMeat/model/UncookedWolfMeat_d.png"),
            s(I + "materials/_res/bloodbag/bloodbag_d.png"),
        ]},
    "veg.mushroom": {
        "label": "mushrooms",
        "region": "primary",
        "samples": [
            s("3rd party/SkythianCat/Hand_Painted_Nature_Kit_LITE/Textures/Boletus_edulis_d.png"),
            s(I + "_res/Bzerkermushroom/model/bzerkermushroom_d.png"),
            s(I + "_res/MistlandsMushrooms/model/MistlandsShrooms_d.png"),
        ]},
    "veg.leaves": {
        "label": "leaves, needles, grass and crops (cutout cards)",
        "region": "primary",
        "samples": [
            s(R + "Beech/materials/beech_leaf.png"),
            s(R + "Birch/materials/birch_leaf.png"),
            s(R + "oak/materials/oak_leaf.png"),
            s(R + "Bush01/textures/Bush01_d.png"),
            s(R + "Shrub02/model/shrub_2.png"),
            s(R + "PineTree/Textures/PineTree_01.png", crop=(0.0, 0.0, 0.5, 1.0)),
            s(NATURE + "Pine_tree_texture_small.png"),
            s(R + "Shoots/materials/ShootLeaf_d.png"),
            s(I + "_res/Kale/model/kale_d.png"),
            s(P + "turnip/model/turnip.png"),
            s(R + "SwampPlant/model/swampplant2_d.png"),
        ]},
    "veg.moss": {
        "label": "moss and ground growth laid over rock and wood",
        "region": "primary",
        "samples": [
            s(NATURE + "stonemoss.png"),
            s(NATURE + "stonemoss_heath.png"),
            s(NATURE + "stonemoss_swamp.png"),
            s(R + "CastleBuildingKit/_res/stonekit_moss.png"),
            s(R + "Dvergr/model/Creep/creep_d.png"),
            s(PLANKS + "Planks5/textures/Planks5c_worn.png"),
        ]},
}
